use data_analysis_project
select * from customer_behaviour_analysis
where category='Clothing' 
order by item_purchased desc

-----------------------------------------------------------------------------------------
-- Business Insights Question
-----------------------------------------------------------------------------------------

--1. Which Category generates highest revenue?
select 
  category,
  round(sum(purchase_amount),2) as Highest_revenue
 from customer_behaviour_analysis
 group by category
 order by Highest_revenue desc
 -- ? Business Problem :- Company does not know which category contributes most to revenue
    
    -- IMPACT 
        -- Helps to prioritise high performing categories
        -- Optimizes inventory planning 
        -- Improves marketing ROI

-- 2 Are discounts actually increase purchase value ?

 select 
  discount_applied,
  round(sum(purchase_amount),2) as Total_revenue,
  round(avg(purchase_amount),2) as Average_value
 from customer_behaviour_analysis
 group by discount_applied
 order by Total_revenue desc

-- ? Business Problems :- Discount may reduce profit without increasing sales.


-- IMPACT :-
         -- Identify effectiveness of discount
         -- Reduce unnecessary discount costs 
         -- Improve profit margins

-- 3 What is the total revenue generated by male and female customer?
 select 
  gender,
  round(sum(purchase_amount),2) as Highest_revenue
 from customer_behaviour_analysis
 group by gender
 order by Highest_revenue desc

 -- ? Business Problem:- Lack of understanding of revenue contribution by genderr segments.
 -- Impact :-
      -- Helps design targeted marketing campaigns
      -- Improves customer segmentation strategy
      -- Enhance personalization efforts

--4. Which customer used a discount but still spent more then the average purchase amount?

 select Top 10
    customer_id,
   round( purchase_amount,2) as purchase_amount,
    discount_applied
    
    from customer_behaviour_analysis
    
    where discount_applied= 'Yes' and
    purchase_amount > (select     -- subquery for Average of purchase_amount
                           avg(purchase_amount)
                         from
                         customer_behaviour_analysis) 

--? Business Problem:- Company cannot identify high -spending customer who are also discount users
   
   -- Impact:- 
       --Identifies premium discount- sensitive customers
       -- Enables targeted discount campaigns 
       -- Improvees customer retentation  and revenue

-- 5 Which are the top/bottom with the highest average review rating
   -- Top 5 
    select top 5
    item_purchased,
    round(avg(review_rating),2) as average_rating
     from customer_behaviour_analysis
     group by item_purchased
     order by average_rating desc
   -- Bottom 5
     select top 5
    item_purchased,
    round(avg(review_rating),2) as average_rating
     from customer_behaviour_analysis
     group by item_purchased
     order by average_rating asc

--? Business Problem :- No Visibility into product performance based on customer satisfaction
-- impact :-
        -- Promotes high-performng products
        -- Improves low-rated products
        -- Enhance customer experience

--6 Average purchase:- Standared vs Express Shipping
select 
 shipping_type,
 count(distinct customer_id) as order_placed,
 round(avg(purchase_amount),2) as avg_purchase,
 round(sum(purchase_amount),2) as revenue

from customer_behaviour_analysis
-- where shipping_type in ('Express','Standard')
group by shipping_type

-- ? Business Problem :- Unclear if faster shipping leads to higher spending.
 -- Impact 
       --Helps optimize shipping pricing strrategy
       --Encourages premium shipping adoption
       -- Increase average order value

-- 7. Do subscribed customers spend more? Compare average speed and total revenue between subscriber
-- and non-subscribers.

select
subscription_status,
count(customer_id),
round(sum(purchase_amount),2) as revenue,
round(avg(purchase_amount),2) as avg_spend
from
customer_behaviour_analysis
group by subscription_status

--? Business Problem:- The effectiveness of subscription program is unknown
-- Impact
        --Validat3es subscription model performance
        --Improves customer loyalty programs
        --Increase customer lifetime value(clv)

-- 8. Top 5 products with highest disount usage %
 select top 5
 item_purchased,
 count(item_purchased) as total_number_of_times_sold,
 count(case discount_applied when'Yes' Then 1 end) as Number_of_Times_discount_applied ,
 count(case discount_applied when 'Yes' Then 1 end)*100.0 /count(item_purchased) as discount_percent
 
 from customer_behaviour_analysis
 group by item_purchased
 order by discount_percent desc

 --? Business Problem :-Some products may be overly dependent on discounts.
 -- Impact :-
              -- Identifies discount - driven products
              -- Helps optimize pricing  strategy
              -- Reduces profit margin loss


--9     Segment customer into new, returning and loyal based on their total number of previous purchase
  -- and show the count of each segment.

  select 
  case  
        when previous_purchases= 0 then 'New_Customer'
        when previous_purchases between 1 and 15 then 'Returning_customer'
        else 'Loyal_Customer'
       end as customer_segment,
       count(*)

   from customer_behaviour_analysis
   group by (  case  
        when previous_purchases= 0 then 'New_Customer'
        when previous_purchases between 1 and 15 then 'Returning_customer'
        else 'Loyal_Customer'
       end)
-- ? Business Problem :- Lack of customer segmentation leads to generic stategies
-- Impact :-
        --Enables personalised marketing 
        --Improves retention strategies
        --Increase conversion rates 

-- 10. What are the top 3 most purchased products within each category
 

/* select
*
from(
select item_purchased,
category,number_of_purchased,
dense_rank() over(partition by category order by number_of_purchased desc) as rank
from(
 select 
  distinct item_purchased,
 category,
 count(item_purchased) over(partition by item_purchased) as number_of_purchased
 from customer_behaviour_analysis) sub1
 ) sub2
 where rank <=3 */

with CTE as 
( select 
  item_purchased,
 category,
 count(item_purchased)  as number_of_purchased,
 RANK() over(partition by category order by count(item_purchased) desc) as rank
 from customer_behaviour_analysis
 group by category,item_purchased 
 )
 select * from CTE
 where rank<=3


--? Business Problem:- The Company does not know top-performing products within categories.
 
 -- impact
      --Improves product placeent &recommendation
      -- Helps inventory optimization
      --Increase sales through best-sellers
--11. Are customes who ae repeat buyers(more than 5 previous purchase) also likely to subscribe

select *,
(number_of_customer*100.0/Total)  as percentage
from(
select * ,sum(number_of_customer) over() as Total
from(
select
  subscription_status,

 count(subscription_status) as number_of_customer
 from customer_behaviour_analysis
 where previous_purchases >5
 group by subscription_status
 ) as sub) sub2


 -- ? Business Problem:- Unclear relationship between loyality and subscription 
 
 -- Impact:-
     -- Improves subscription targeting
     -- Inrease conversion to paid programs
     -- Increase customer retention strategy

 
 -- 12. What is The revenue contribution of each age group

 select 
 distinct age
 from customer_behaviour_analysis
 order by age asc

 select 
 case 
    when age between 18 and 25 then '18-25'
    when age between 26 and 35 then '26-35'
    when age between 36 and 50 then '36-50'

    else '51+'
    end as age_group,
    round(sum(purchase_amount),2) as Total_revenue
   from customer_behaviour_analysis
   group by (case 
    when age between 18 and 25 then '18-25'
    when age between 26 and 35 then '26-35'
    when age between 36 and 50 then '36-50'
 
    else '51+'
    end )
    order by age_group desc
--? Business Problem :- No visibility into which age group contributes most to revenue.
-- Impact:- 
      --Enables age-based targeting
      --Enhance marketing efficiency










































































































































                        

     


